{
  description = "KooL's NixOS-Hyprland";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-25.11";
    nixpkgs-unstable.url = "github:nixos/nixpkgs/nixos-unstable";

    home-manager.url = "github:nix-community/home-manager/release-25.11";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";

    nixvim.url = "github:nix-community/nixvim/main";

    alejandra.url = "github:kamadorueda/alejandra";

    ags = {
      type = "github";
      owner = "aylur";
      repo = "ags";
      ref = "v1";
    };

    catppuccin = {
      url = "github:catppuccin/nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    quickshell = {
      # Official mirror per quickshell docs; avoids outfoxxed.me DNS outages.
      url = "github:quickshell-mirror/quickshell";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = inputs @ {
    self,
    nixpkgs,
    nixpkgs-unstable,
    alejandra,
    ...
  }: let
    # -----------------------------------------------------------------------
    # Global system
    # -----------------------------------------------------------------------
    system = "x86_64-linux";

    # -----------------------------------------------------------------------
    # Machine-local host root
    #
    # hosts/default/
    #     Centrally managed template.
    #
    # .local-host/<hostname>/
    #     Machine-specific configuration generated by the installer.
    #
    # .local-host is intentionally Git-ignored.
    #
    # IMPORTANT:
    #
    # The installer evaluates this flake using:
    #
    #   path:/absolute/path/to/repository
    #
    # This allows Nix to see the machine-local files.
    # -----------------------------------------------------------------------
    localHostRoot = ./. + "/.local-host";

    # -----------------------------------------------------------------------
    # Discover machine-local hosts.
    #
    # Every directory under .local-host/ becomes a NixOS configuration.
    #
    # Example:
    #
    #   .local-host/bakadesk-2657013e362a/
    #
    # becomes:
    #
    #   nixosConfigurations.bakadesk-2657013e362a
    # -----------------------------------------------------------------------
    localHostEntries =
      if builtins.pathExists localHostRoot
      then builtins.readDir localHostRoot
      else {};

    hostNames =
      builtins.filter
        (
          name:
            localHostEntries.${name} == "directory"
        )
        (builtins.attrNames localHostEntries);

    # -----------------------------------------------------------------------
    # Host identity
    #
    # Every machine-local host must contain:
    #
    #   .local-host/<hostname>/identity.json
    #
    # Example:
    #
    #   {
    #     "username": "baka"
    #   }
    # -----------------------------------------------------------------------
    hostIdentity = host: let
      hostDir = localHostRoot + "/${host}";
      identityPath = hostDir + "/identity.json";

      identity =
        if builtins.pathExists identityPath
        then builtins.fromJSON (builtins.readFile identityPath)
        else {};
    in {
      username =
        if identity ? username && identity.username != null
        then identity.username
        else throw ''
          Host '${host}' is missing a username.

          Expected:

            .local-host/${host}/identity.json

          containing for example:

            {
              "username": "baka"
            }

          The installer must create identity.json before this host
          can be evaluated.
        '';
    };

    # -----------------------------------------------------------------------
    # Host variables
    #
    # Machine-specific variables are loaded from:
    #
    #   .local-host/<hostname>/variables.nix
    #
    # This is intentionally NOT:
    #
    #   hosts/<hostname>/variables.nix
    #
    # The resulting attribute set is passed to both NixOS and Home Manager
    # through specialArgs / extraSpecialArgs.
    #
    # Home Manager modules should consume:
    #
    #   hostVars
    #
    # instead of importing hosts/${host}/variables.nix themselves.
    # -----------------------------------------------------------------------
    hostVariables = host: let
      hostDir = localHostRoot + "/${host}";
      variablesPath = hostDir + "/variables.nix";
    in
      if builtins.pathExists variablesPath
      then import variablesPath
      else throw ''
        Host '${host}' is missing variables.nix.

        Expected:

          .local-host/${host}/variables.nix

        The installer should create this file from:

          hosts/default/variables.nix
      '';

    # -----------------------------------------------------------------------
    # Packages
    # -----------------------------------------------------------------------
    pkgs = import nixpkgs {
      inherit system;

      config = {
        allowUnfree = true;
      };
    };

    pkgsUnstable = import nixpkgs-unstable {
      inherit system;

      config = {
        allowUnfree = true;
      };
    };

    waybarWeatherPkg =
      pkgs.callPackage ./pkgs/waybar-weather.nix {};

    clawCodeLocalPkg =
      pkgs.callPackage ./pkgs/claw-code-local.nix {};

  in {
    # =======================================================================
    # Packages
    # =======================================================================

    packages.${system} = {
      waybar-weather = waybarWeatherPkg;
      claw-code-local = clawCodeLocalPkg;
    };

    # =======================================================================
    # NixOS configurations
    #
    # Every directory under .local-host/ becomes:
    #
    #   nixosConfigurations.<hostname>
    #
    # hosts/default/ is NEVER treated as a machine.
    # =======================================================================

    nixosConfigurations =
      builtins.listToAttrs (
        map
          (
            host:
              let
                # -----------------------------------------------------------
                # Machine identity
                # -----------------------------------------------------------
                identity = hostIdentity host;
                username = identity.username;

                # -----------------------------------------------------------
                # Machine-local host directory
                # -----------------------------------------------------------
                hostDir =
                  localHostRoot + "/${host}";

                # -----------------------------------------------------------
                # Machine-local variables
                #
                # Loaded once and passed into Home Manager as `hostVars`.
                # -----------------------------------------------------------
                hostVars =
                  hostVariables host;

              in {
                name = host;

                value = nixpkgs.lib.nixosSystem {
                  inherit system;

                  # ---------------------------------------------------------
                  # NixOS special arguments
                  #
                  # These are available to NixOS modules as:
                  #
                  #   inputs
                  #   username
                  #   host
                  #   pkgsUnstable
                  #   hostVars
                  # ---------------------------------------------------------
                  specialArgs = {
                    inherit
                      inputs
                      username
                      host
                      pkgsUnstable
                      hostVars;
                  };

                  modules = [
                    # -------------------------------------------------------
                    # Machine-local host configuration
                    #
                    # Everything machine-specific comes from:
                    #
                    #   .local-host/<hostname>/
                    # -------------------------------------------------------
                    (hostDir + "/config.nix")

                    # -------------------------------------------------------
                    # Centrally managed modules
                    # -------------------------------------------------------
                    ./modules/overlays.nix
                    ./modules/desktop
                    ./modules/packages.nix
                    ./modules/custom-ui
                    ./modules/tools

                    {
                      nixpkgs.config.allowBroken = true;
                    }

                    ./modules/fonts.nix
                    ./modules/security/default.nix
                    ./modules/entra
                    ./modules/power.nix

                    # -------------------------------------------------------
                    # Home Manager
                    # -------------------------------------------------------
                    inputs.home-manager.nixosModules.home-manager

                    {
                      home-manager.useGlobalPkgs = true;
                      home-manager.useUserPackages = true;

                      home-manager.backupFileExtension = "hm-bak";
                      home-manager.overwriteBackup = true;

                      # -----------------------------------------------------
                      # Home Manager special arguments
                      #
                      # IMPORTANT:
                      #
                      # Home Manager modules can now receive:
                      #
                      #   hostVars
                      #
                      # directly.
                      #
                      # They should NOT import:
                      #
                      #   ../../../hosts/${host}/variables.nix
                      #
                      # anymore.
                      # -----------------------------------------------------
                      home-manager.extraSpecialArgs = {
                        inherit
                          inputs
                          system
                          username
                          host
                          hostVars;
                      };

                      home-manager.users.${username} = {
                        home.username = username;
                        home.homeDirectory = "/home/${username}";
                        home.stateVersion = "24.05";

                        imports = [
                          ./modules/home/default.nix
                        ];
                      };
                    }
                  ];
                };
              }
          )
          hostNames
      );

    # =======================================================================
    # Formatter
    # =======================================================================

    formatter.${system} =
      alejandra.defaultPackage.${system};
  };
}
