{
  description = "KooL's NixOS-Hyprland";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-25.11";
    nixpkgs-unstable.url = "github:nixos/nixpkgs/nixos-unstable";

    home-manager.url = "github:nix-community/home-manager/release-25.11";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";

    nixvim.url = "github:nix-community/nixvim/main";

    alejandra.url = "github:kamadorueda/alejandra";

    ags = {
      type = "github";
      owner = "aylur";
      repo = "ags";
      ref = "v1";
    };

    catppuccin = {
      url = "github:catppuccin/nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    quickshell = {
      # Official mirror per quickshell docs; avoids outfoxxed.me DNS outages.
      url = "github:quickshell-mirror/quickshell";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = inputs @ {
    self,
    nixpkgs,
    nixpkgs-unstable,
    ags,
    alejandra,
    ...
  }: let
    system = "x86_64-linux";

    # -----------------------------------------------------------------------
    # Host discovery
    #
    # hosts/default is the centrally managed template.
    # All other host directories are machine-local and generated by the
    # installer. They are intentionally NOT required to be Git-tracked.
    # -----------------------------------------------------------------------
    hostEntries = builtins.readDir ./hosts;

    hostNames =
      builtins.filter
        (
          name:
            name != "default"
            && hostEntries.${name} == "directory"
        )
        (builtins.attrNames hostEntries);

    # -----------------------------------------------------------------------
    # Read machine-local host identity.
    #
    # Every generated host must have:
    #
    #   hosts/<hostname>/identity.json
    #
    # containing at least:
    #
    #   {
    #     "username": "..."
    #   }
    # -----------------------------------------------------------------------
    hostIdentity = host: let
      identityPath = ./. + "/hosts/${host}/identity.json";

      identity =
        if builtins.pathExists identityPath
        then builtins.fromJSON (builtins.readFile identityPath)
        else {};
    in {
      username =
        if identity ? username
        then identity.username
        else throw ''
          Host '${host}' is missing a username in:

            hosts/${host}/identity.json

          The installer must create identity.json before this host can
          be evaluated.
        '';
    };

    # -----------------------------------------------------------------------
    # Packages
    # -----------------------------------------------------------------------
    pkgs = import nixpkgs {
      inherit system;

      config = {
        allowUnfree = true;
      };
    };

    pkgsUnstable = import nixpkgs-unstable {
      inherit system;

      config = {
        allowUnfree = true;
      };
    };

    waybarWeatherPkg =
      pkgs.callPackage ./pkgs/waybar-weather.nix {};

    clawCodeLocalPkg =
      pkgs.callPackage ./pkgs/claw-code-local.nix {};

  in {
    # -----------------------------------------------------------------------
    # Packages
    # -----------------------------------------------------------------------
    packages.${system} = {
      waybar-weather = waybarWeatherPkg;
      claw-code-local = clawCodeLocalPkg;
    };

    # -----------------------------------------------------------------------
    # Dynamically generated NixOS configurations
    #
    # A directory appearing at:
    #
    #   hosts/<hostname>/
    #
    # automatically becomes:
    #
    #   nixosConfigurations.<hostname>
    #
    # No modification to flake.nix is required.
    # -----------------------------------------------------------------------
    nixosConfigurations =
      builtins.listToAttrs (
        map
          (
            host:
              let
                identity = hostIdentity host;
                username = identity.username;
              in {
                name = host;

                value = nixpkgs.lib.nixosSystem rec {
                  specialArgs = {
                    inherit
                      system
                      inputs
                      username
                      host
                      pkgsUnstable;
                  };

                  modules = [
                    (./. + "/hosts/${host}/config.nix")

                    ./modules/overlays.nix
                    ./modules/desktop
                    ./modules/packages.nix
                    ./modules/custom-ui
                    ./modules/tools

                    {
                      nixpkgs.config.allowBroken = true;
                    }

                    ./modules/fonts.nix
                    ./modules/security/default.nix
                    ./modules/entra
                    ./modules/power.nix

                    inputs.home-manager.nixosModules.home-manager

                    {
                      home-manager.useGlobalPkgs = true;
                      home-manager.useUserPackages = true;
                      home-manager.backupFileExtension = "hm-bak";
                      home-manager.overwriteBackup = true;

                      home-manager.extraSpecialArgs = {
                        inherit
                          inputs
                          system
                          username
                          host;
                      };

                      home-manager.users.${username} = {
                        home.username = username;
                        home.homeDirectory = "/home/${username}";
                        home.stateVersion = "24.05";

                        imports = [
                          ./modules/home/default.nix
                        ];
                      };
                    }
                  ];
                };
              }
          )
          hostNames
      );

    # -----------------------------------------------------------------------
    # Code formatter
    # -----------------------------------------------------------------------
    formatter.x86_64-linux =
      alejandra.defaultPackage.x86_64-linux;
  };
}
